(((:ADJACENCIES "graphnode21" ((:NODE-TO . "graphnode1") (:NODE-FROM . "graphnode0") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode13") (:NODE-FROM . "graphnode0") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode14") (:NODE-FROM . "graphnode0") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode15") (:NODE-FROM . "graphnode0") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode16") (:NODE-FROM . "graphnode0") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode17") (:NODE-FROM . "graphnode0") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#83548B") (:$TYPE . "circle") (:$DIM . 10)) (:ID . "graphnode0") (:NAME . "graphnode0"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode2") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode4") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode5") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode6") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode7") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode8") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode10") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode11") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode12") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode13") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode14") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode15") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode16") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode17") (:NODE-FROM . "graphnode1") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#EBB056") (:$TYPE . "circle") (:$DIM . 11)) (:ID . "graphnode1") (:NAME . "graphnode1"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode5") (:NODE-FROM . "graphnode2") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode9") (:NODE-FROM . "graphnode2") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode18") (:NODE-FROM . "graphnode2") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#416D9C") (:$TYPE . "circle") (:$DIM . 7)) (:ID . "graphnode2") (:NAME . "graphnode2"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode5") (:NODE-FROM . "graphnode3") (:DATA (:$COLOR . "#909291")))
                ((:NODE-TO . "graphnode9") (:NODE-FROM . "graphnode3") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode10") (:NODE-FROM . "graphnode3") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode12") (:NODE-FROM . "graphnode3") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#416D9C") (:$TYPE . "square") (:$DIM . 10)) (:ID . "graphnode3") (:NAME . "graphnode3"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#83548B") (:$TYPE . "square") (:$DIM . 11)) (:ID . "graphnode4") (:NAME . "graphnode4"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode9") (:NODE-FROM . "graphnode5") (:DATA (:$COLOR . "#909291"))))
  (:DATA (:$COLOR . "#C74243") (:$TYPE . "triangle") (:$DIM . 8)) (:ID . "graphnode5") (:NAME . "graphnode5"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode10") (:NODE-FROM . "graphnode6") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode11") (:NODE-FROM . "graphnode6") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#83548B") (:$TYPE . "circle") (:$DIM . 11)) (:ID . "graphnode6") (:NAME . "graphnode6"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#EBB056") (:$TYPE . "triangle") (:$DIM . 12)) (:ID . "graphnode7") (:NAME . "graphnode7"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#C74243") (:$TYPE . "star") (:$DIM . 10)) (:ID . "graphnode8") (:NAME . "graphnode8"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#83548B") (:$TYPE . "circle") (:$DIM . 12)) (:ID . "graphnode9") (:NAME . "graphnode9"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode11") (:NODE-FROM . "graphnode10") (:DATA (:$COLOR . "#909291"))))
  (:DATA (:$COLOR . "#70A35E") (:$TYPE . "triangle") (:$DIM . 11)) (:ID . "graphnode10") (:NAME . "graphnode10"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#70A35E") (:$TYPE . "circle") (:$DIM . 11)) (:ID . "graphnode11") (:NAME . "graphnode11"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#83548B") (:$TYPE . "triangle") (:$DIM . 10)) (:ID . "graphnode12") (:NAME . "graphnode12"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode14") (:NODE-FROM . "graphnode13") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#EBB056") (:$TYPE . "star") (:$DIM . 7)) (:ID . "graphnode13") (:NAME . "graphnode13"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#EBB056") (:$TYPE . "triangle") (:$DIM . 12)) (:ID . "graphnode14") (:NAME . "graphnode14"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode16") (:NODE-FROM . "graphnode15") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode17") (:NODE-FROM . "graphnode15") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#83548B") (:$TYPE . "triangle") (:$DIM . 11)) (:ID . "graphnode15") (:NAME . "graphnode15"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode17") (:NODE-FROM . "graphnode16") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#C74243") (:$TYPE . "star") (:$DIM . 7)) (:ID . "graphnode16") (:NAME . "graphnode16"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#416D9C") (:$TYPE . "circle") (:$DIM . 7)) (:ID . "graphnode17") (:NAME . "graphnode17"))
 ((:ADJACENCIES ((:NODE-TO . "graphnode19") (:NODE-FROM . "graphnode18") (:DATA (:$COLOR . "#557EAA")))
                ((:NODE-TO . "graphnode20") (:NODE-FROM . "graphnode18") (:DATA (:$COLOR . "#557EAA"))))
  (:DATA (:$COLOR . "#EBB056") (:$TYPE . "triangle") (:$DIM . 9)) (:ID . "graphnode18") (:NAME . "graphnode18"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#70A35E") (:$TYPE . "circle") (:$DIM . 8)) (:ID . "graphnode19") (:NAME . "graphnode19"))
 ((:ADJACENCIES) (:DATA (:$COLOR . "#C74243") (:$TYPE . "star") (:$DIM . 8)) (:ID . "graphnode20") (:NAME . "graphnode20")))


